### PR TITLE
Enable parsing of tables containing pipes

### LINKED ISSUE #19: Tables can't have cells containing escaped pipe characters
Hello,

I  have a table with cell values that contain pipe characters, such as the first cell on the second row in this table:
```
| MatterTypeFullPath                        | ApprovedTax | ApprovedTotalExcludingTax | LockedExchangeRate |
| Litigation/Dispute\|Potential Dispute     | 12.0        |  133.09                                  | 1.0                               |
```
Escaping the pipe character works fine in most Gherkin engines AFAIK. But here it doesn't.
Is there a workaround?

Thanks!

### PR DESCRIPTION
**Pull request by maxmarcon**
Fixes #19

### CODE REVIEW

**Comment by maxmarcon** [comment]
@revati I don't know if someone is still maintaining this project, but let me know if I can do anything to speed up the process of getting this PR merged. Thanks.

**Comment by maxmarcon** [comment]
hey @mgwidmann, politely pinging and asking if there's any chance we can merge this. Thanks 👍

**Comment by maxmarcon** [comment]
hi @mgwidmann , pinging again since I got no answer. If you're not interested in maintaining this project anymore, I could take over. Thanks

**Comment by mgwidmann** [comment]
Apologies for missing this, I'm not involved with this project anymore. Looks like we need the build fixed at this point though before we can merge anything.

**Comment by maxmarcon** [comment]
The build is broken because of a problem with the setup of the CI pipeline. If you make me an owner, I'd be happy to make sure it works again

**Pull request merged**
