### PR TITLE
Rewrite Gherkin to support Rule keyword

### PR DESCRIPTION
**Pull request by mononym**
Implementing Rule support required a reworking of the Gherkin parser, at least for how I thought about the process anyway.

NOTE: This change is backwards incompatible from the perspective of Cabbage, but will not break any existing feature files. What it will do is allow for Rules to be defined as well. I also have updated Cabbage to work with the new code, so once/if this is pulled I can put in the pull request for Cabbage which will bring everything into line.

As indentation is not checked as part of parsing, once a Rule has been defined all subsequent scenarios are assumed to be a part of one Rule or another. As a feature file should have no rules, or define everything in terms of Rules, this shouldn't be an issue. Even then, the issue would lie in the Cabbage package where such assumptions might be made and not here.

### CODE REVIEW

**Comment by mononym** [comment]
Note that the changes in Cabbage which account for the breaking change (It's the changing of the different step structs into a single one with a keyword field to closer match the Gherkin AST definition) are in a pull request which I haven't made yet which is for Rules.

Please see ongoing discussion here: https://github.com/cabbage-ex/cabbage/pull/62

**Comment by mononym** [comment]
The failure here is the same as the failure here: https://github.com/cabbage-ex/gherkin/pull/7

**Comment by revati** [comment]
CI testing have failed because of version incompatability: 
```
** (Mix) You're trying to run :gherkin on Elixir v1.2.6 but it has declared in its mix.exs file it supports only Elixir ~> 1.3
```

Can someone (most likely @mgwidmann) fix needed elixir version in `Semaphore`?
Or you could give me full access to project settings and semiphore.

`~> 1.3` is minimal supported version by this library. But we support further versions as well, so test should be ran on all [those](https://semaphoreci.com/docs/elixir-continuous-integration.html#ci-environment-for-elixir-projects) versions:

- 1.3.4
- 1.4.5
- 1.5.3
- 1.6.6
- 1.7.3

**Comment by nicholasjhenry** [comment]
@revati You're best bet to get a response is to direct message @mgwidmann on the Elixir Forum. I would add you to Semaphore but I don't have admin privileges.

**Comment by revati** [comment]
@nicholasjhenry found him and asked there. Will see what his response will be.
Worst case scenario will be, I will start my own gherkin ExUnit based library with blackjack and hookers.

**Comment by nicholasjhenry** [comment]
@revati I've sent you an invite for Semaphore.

**Comment by revati** [comment]
Thanks, noticed and fixed it. It's odd. @mgwidmann told that he has given all permissions to you (
@nicholasjhenry), but in organization page, there still is only one human: him.

**Pull request merged**
